# sets maximal velocity and acceleration values along the trajectory
dynamic_params: {
  max_v: 5.0,
  max_a: 2.0
}

waypoints: {
  position: [[10.0, 0.0, 3.0], [20.0, 5.0, 3.0], [25.0, 7.5, 3.0], [30.0, 10.0, 3.0], [35.0, 25.0, 13.0], [35.0, 35.0, 6.0], [25.0, 39.0, 11.0], [16.0, 39.0, 11.0], [12.0, 39.0, 11.0], [8.0, 39.0, 11.0]], 
  velocity: [[], [], [], [], [], [], [], [], [0.0, 0.0, 0.0], []], 
  acceleration: [[], [], [], [], [], [], [], [], [0.0, 0.0, 0.0], []]
  # your waypoints here. Think about how to best add any number of waypoints
  # and the according velocity and acceleration constraints.
}

